spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_dining?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/


